title: docs.data.gouv.test
description: Test déploiement du blog docs.data.gouv.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://staticweb01-etalab.gouv.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  etalab


# Exclude from processing.
exclude:
   - Gemfile.lock
   - deploy

defaults:
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
