title: docs.data.gouv.test
description: Test déploiement du blog docs.data.gouv.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://staticweb01-etalab.gouv.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  etalab


# Exclude from processing.
exclude:
   - Gemfile.lock
   - deploy

defaults:
  -
    scope:
      path: "pages"  # means "all files"
    values:
      layout: page


plugins:
  - jekyll-feed

themeColor: blue # green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages,_posts]
exclude: [_site,deploy]
sass:
  style: compressed

